---
- name: Examen
  hosts: node1
  tasks:
    - name: Creates directory
      file:
        path: /src/exam
        state: directory
      become: yes
    
    - name: Creating a file with content
      copy:
        dest: "/src/exam/essen.txt"
        content: |
          "Lachsnudeln"
      become: yes

    - name: Creating a file with content
      copy:
        dest: "/src/exam/datum.txt"
        content: |
          "25.06.2021"
      become: yes

    - name: Creating a file with content
      copy:
        dest: "/src/exam/ip.txt"
        content: |
          "35.157.153.55"
      become: yes