---
- name: Examen
  hosts: node1
  tasks:
    - name: Creates directory
      file:
        path: /src/exam
        state: directory
      become: yes
    
    - name: Creating a file with content
      copy:
        dest: "/src/exam/essen.txt"
        content: "{{food}}"
      become: yes

    - name: Creating a file with content
      copy:
        dest: "/src/exam/datum.txt"
        content: "{{date}}"
      become: yes

    - name: Creating a file with content
      copy:
        dest: "/src/exam/ip.txt"
        content: "{{ip}}"
      become: yes